blank_issues_enabled: false
contact_links:
  - name: Ask for Help
    url: https://github.com/yannickberk/skills-expand-your-team-with-copilot/discussions
    about: Get help or discuss ideas with the community
